#!/usr/bin/env bash
set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Port forward of service
##?
##? Usage:
##?   forwardsvc PORT
docs::parse "$@"

echo "Select the namespace to see the services:"
ns=$(kubectl get ns | fzf --height 30% --layout reverse  | awk '{print $1}')

echo "Select the service to see the ports:"
svc=$(kubectl get svc -n $ns | fzf --height 30% --layout reverse  | awk '{print $1}')

echo "Select the port to port-forward:"
port=$(kubectl get svc $svc -n $ns --template='{{range .spec.ports}}{{.port}} {{.protocol}}{{"\n"}}{{end}}' | fzf --height 30% --layout reverse  | awk '{print $1}')

kubectl port-forward service/"$svc" "$1":"$port" -n "$ns"