#!/usr/bin/env bash
set -euo pipefail

source "$DOTLY_PATH/scripts/core/_main.sh"

##? Disable record mode
##?
##? Usage:
##?   off
docs::parse "$@"

powershell -command "&{\$p='HKCU:SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\StuckRects3';\$v=(Get-ItemProperty -Path \$p).Settings;\$v[8]=2;&Set-ItemProperty -Path \$p -Name Settings -Value \$v;&Stop-Process -f -ProcessName explorer}"
qres /x:2560 /y:1080
